/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.12).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.AddUserRequest;
import io.swagger.model.CreatedUser;
import io.swagger.model.Error;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-01-20T08:14:21.754Z")

@Api(value = "add-an-user", description = "the add-an-user API")
@RequestMapping(value = "/openBanking/v1")
public interface AddAnUserApi {

    @ApiOperation(value = "Add an user", nickname = "addUserRequest", notes = "Add an user. ", response = CreatedUser.class, authorizations = {
        @Authorization(value = "Oauth2", scopes = {
            
            })
    }, tags={ "BDD Demo API", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "User Added", response = CreatedUser.class),
        @ApiResponse(code = 400, message = "Bad Request", response = Error.class),
        @ApiResponse(code = 401, message = "Unauthorized", response = Error.class),
        @ApiResponse(code = 403, message = "Forbidden.", response = Error.class),
        @ApiResponse(code = 500, message = "Server-side error", response = Error.class) })
    @RequestMapping(value = "/add-an-user",
        produces = { "application/json; charset=utf-8" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
     ResponseEntity<CreatedUser> addUserRequest(@ApiParam(value = "Add User"  )  @Valid @RequestBody AddUserRequest addUserRequest);

}
